config_path: '/home/wiseman/code/des_sn_hosts/simulations/config/DES_BS20.yaml'
Rv_lo:
    lo: 1.5
    hi: 2.75
    step: 0.25
Rv_hi:
    lo: 2.5
    hi: 4.00
    step: 0.25
age_step:
    lo: 0.0
    hi: 0.25
    step: 0.05
save:
    dir: 'BS20_Rv_lo_cut'

n_samples: 150000
