
hostlib_fn: /media/data3/wiseman/des/AURA/all_model_params_z0.05_1.20_av0.00_1.00_rv_rand_full_age_dists_neb_U-2.00_res_2.h5
config:
  root_dir: $AURA_DIR
SN_rv_model:
  model: mass_rv_step
  params:
    rv_low: 2.8
    rv_high: 2.2
    rv_sig_low: 0.5
    rv_sig_high: 0.5
    mass_split: 10

Host_Av_model:
  model: choose_Av_SN_E_Rv_norm
  params:
    Rv_mu: 2.7
    Rv_sig: 1.5
    Av_sig: 0.5

SN_E_model:
  model: E_exp_mass
  params:
    Tau_low: 0.12
    Tau_high: 0.15
    mass_split: 10

SN_colour_model:
  model: c_int_plus_dust
  params:
    c_int_type: norm
    c_int_params:
      mu: -0.084
      sig: 0.04

x1_model:
  model: x1_twogauss_age
  params:
    mu_old: -1.3
    sig_old: 0.65
    mu_young: 0.15
    sig_young: 0.75
    old_prob: 0.5
    age_step_loc: 1

mB_model:
  model: tripp_rv_popn_alpha_beta
  params:
    mu_alpha: 0.15
    sig_alpha: 0.02
    mu_beta: 2.0
    sig_beta: 0.1
    M0: -19.375
    sigma_int: 0.1
    mass_step:
      mag: 0.0
      loc: 10
    age_step:
      mag: 0.0
      loc: 1

