
hostlib_fn: /media/data3/wiseman/des/AURA/sims/hostlibs/all_model_params_quench_BC03_z0.0005_1.400_av0.00_1.50_rv_rand_full_age_dists_neb_U-2.00_res_2_beta_1.14_combined.h5
config:
  root_dir: $AURA_DIR
  efficiency_dir: /media/data3/wiseman/des/desdtd/
SN_rv_model:
  model: age_rv_step
  params:
    rv_young: 2.94
    rv_old: 2.4
    rv_sig_young: 1.0
    rv_sig_old: 1.0
    age_split: 3
    rv_min: 0.5

Host_Av_model:
  model: choose_Av_SN_E_Rv_step
  params:
    Rv_mu_low: 2.6
    Rv_sig_low: 0.5
    Rv_mu_high: 3.1
    Rv_sig_high: 0.5
    Av_sig: 0.5
    mass_split: 10

SN_E_model:
  model: E_exp_age
  params:
    Tau_low: 0.12
    Tau_high: 0.15
    age_split: 3

SN_colour_model:
  model: c_int_plus_dust
  params:
    c_int_type: norm
    c_int_params:
      mu: -0.075
      sig: 0.042
      e_noise: 0.03

x1_model:
  model: x1_twogauss_age
  params:
    mu_young: 0.25
    sig_young: 0.61
    mu_old: -1.22
    sig_old: 0.56
    age_step_loc: 0.75
    old_prob: 0.75
mB_model:
  model: tripp_rv_popn_alpha_beta
  params:
    mu_alpha: 0.22
    sig_alpha: 0.0001
    mu_beta: 1.98
    sig_beta: 0.35
    M0: -19.375
    sigma_int: 0.08
    mass_step:
      mag: 0.0
      loc: 10
    age_step:
      mag: 0.0
      loc: 0.75

mu_res_fitter:
  fitter: fit_mu_res_nostep
  params:
    fix_alpha: False
    fix_beta: False
