hostlib_fn: /media/data3/wiseman/des/AURA/sims/hostlibs/all_model_params_BC03_z0.15_0.85_av0.00_1.00_rv_rand_full_age_dists_neb_U-2.00_res_2_beta_1.14.h5
config:
  root_dir: $AURA_DIR
  efficiency_dir: /media/data3/wiseman/des/desdtd/
SN_rv_model:
  model: mass_rv_step
  params:
    rv_low: 3.2323901
    rv_high: 1.65167972
    rv_sig_low: 0.95962879
    rv_sig_high: 1.27678934
    mass_split: 10
    rv_min: 0.5
Host_Av_model:
  model: choose_Av_SN_E_Rv_step
  params:
    Rv_mu_low: 2.6
    Rv_sig_low: 0.5
    Rv_mu_high: 3.1
    Rv_sig_high: 0.5
    Av_sig: 0.5
    mass_split: 10

SN_E_model:
  model: E_exp_mass
  params:
    Tau_low: 0.13770023
    Tau_high: 0.13986979
    mass_split: 3

SN_colour_model:
  model: c_int_plus_dust
  params:
    c_int_type: norm
    c_int_params:
      mu: -0.05090641
      sig: 0.05282635
      e_noise: 0.03

x1_model:
  model: x1_twogauss_age
  params:
    mu_young: 0.25
    sig_young: 0.6
    mu_old: -1.2
    sig_old: 0.6
    age_step_loc: 0.75
    old_prob: 0.75


mB_model:
  model: tripp_rv_popn_alpha_beta
  params:
    mu_alpha: 0.21
    sig_alpha: 0.0001
    mu_beta: 1.51045692
    sig_beta: 0.47675452
    M0: -19.375
    sigma_int: 0.
    mass_step:
      mag: 0.0
      loc: 10
    age_step:
      mag: 0.0
      loc: 0.6

mu_res_fitter:
  fitter: fit_mu_res_nostep
  params:
    fix_alpha: False
    fix_beta: False
