hostlib_fn: /media/data3/wiseman/des/AURA/sims/hostlibs/all_model_params_quench_bursts_BC03_z0.14000_1.26000_av0.00_1.50_rv_rand_full_age_dists_neb_U-2.00_res_2_beta_1.14_combined.h5
config:
  root_dir: $AURA_DIR
  efficiency_dir: /media/data3/wiseman/des/desdtd/
SN_rv_model:
  model: mass_rv_step
  params:
    rv_low: 2.75
    rv_high: 1.5
    rv_sig_low: 1.3
    rv_sig_high: 1.3
    mass_split: 10
    rv_min: 0.5

Host_Av_model:
  model: choose_Av_SN_E_Rv_norm
  params:
    Rv_mu: 2.7
    Rv_sig: 1.5
    Av_sig: 0.5

SN_E_model:
  model: E_exp_mass
  params:
    Tau_low: 0.135
    Tau_high: 0.135
    mass_split: 10

SN_colour_model:
  model: c_int_plus_dust
  params:
    c_int_type: norm
    c_int_params:
      mu: -0.075
      sig: 0.042
      e_noise: 0.035
x1_model:
  model: x1_int_asymm
  params:
    mu: 0.673
    sig_minus: 1.45
    sig_plus: 0.222

mB_model:
  model: tripp_rv_popn_alpha_beta
  params:
    mu_alpha: 0.15
    sig_alpha: 0.0001
    mu_beta: 1.98
    sig_beta: 0.35
    M0: -19.375
    sigma_int: 0.
    mass_step:
      mag: 0.0
      loc: 10
    age_step:
      mag: 0.0
      loc: 1

mu_res_fitter:
  fitter: fit_mu_res_nostep
  params:
    fix_alpha: False
    fix_beta: False
