
hostlib_fn: /media/data3/wiseman/des/AURA/sims/hostlibs/all_model_params_quench_BC03_z0.00050_1.32000_av0.00_1.50_rv_rand_full_age_dists_neb_U-2.00_res_2_beta_1.13_combined.h5
config:
  root_dir: $AURA_DIR
  efficiency_dir: /media/data3/wiseman/des/desdtd/
SN_rv_model:
  model: age_rv_step
  params:
    rv_young: 2.75
    rv_old: 2.75
    rv_sig_young: 1.3
    rv_sig_old: 1.3
    age_split: 3
    rv_min: 1.2

Host_Av_model:
  model: choose_Av_SN_E_Rv_step
  params:
    Rv_mu_low: 2.6
    Rv_sig_low: 0.5
    Rv_mu_high: 3.1
    Rv_sig_high: 0.5
    Av_sig: 0.5
    mass_split: 10
SN_E_model:
  model: E_exp_age
  params:
    Tau_low: 0.12
    Tau_high: 0.15
    age_split: 3

SN_colour_model:
  model: c_int_plus_dust
  params:
    c_int_type: norm
    c_int_params:
      mu: -0.084
      sig: 0.04
      e_noise: 0.02

x1_model:
  model: x1_twogauss_age
  params:
    mu_young: 0.15
    sig_young: 0.60
    mu_old: -1.3
    sig_old: 0.65
    age_step_loc: 0.8
    old_prob: 0.5

mB_model:
  model: tripp_rv_popn_alpha_beta
  params:
    mu_alpha: 0.15
    sig_alpha: 0.001
    mu_beta: 2.
    sig_beta: 0.35
    M0: -19.375
    sigma_int: 0.
    mass_step:
      mag: 0.0
      loc: 10
    age_step:
      mag: 0.2
      loc: 0.8

mu_res_fitter:
  fitter: fit_mu_res_nostep
  params:
    fix_alpha: False
    fix_beta: False
c_perfect: False
