
hostlib_fn: /media/data3/wiseman/des/AURA/sims/hostlibs/all_model_params_BC03_z0.05_0.63_av0.00_1.50_rv_rand_full_age_dists_neb_U-2.00_res_2.h5
config:
  root_dir: $AURA_DIR
SN_rv_model:
  model: mass_rv_step
  params:
    rv_low: 3.1
    rv_high: 2.6
    rv_sig_low: 1.3
    rv_sig_high: 1.3
    mass_split: 10.0

Host_Av_model:
  model: choose_Av_SN_E_Rv_step
  params:
    Rv_mu_low: 2.6
    Rv_sig_low: 0.5
    Rv_mu_high: 3.1
    Rv_sig_high: 0.5
    Av_sig: 0.5
    mass_split: 10
SN_E_model:
  model: E_exp_mass
  params:
    Tau_low: 0.12
    Tau_high: 0.15
    mass_split: 10

SN_colour_model:
  model: c_int_plus_dust
  params:
    c_int_type: norm
    c_int_params:
      mu: -0.084
      sig: 0.04

x1_model:
  model: x1_twogauss_age
  params:
    mu_young: 0.15
    sig_young: 0.75
    mu_old: -1.3
    sig_old: 0.65
    age_step_loc: 1
    old_prob: 0.5

mB_model:
  model: tripp_rv_popn_alpha_beta
  params:
    mu_alpha: 0.15
    sig_alpha: 0.02
    mu_beta: 1.5
    sig_beta: 0.35
    M0: -19.375
    sigma_int: 0.
    mass_step:
      mag: 0.0
      loc: 10
    age_step:
      mag: 0.0
      loc: 1

mu_res_fitter:
  fitter: fit_mu_res_nostep
  params:
    fix_alpha: False
    fix_beta: 3.07
